language: cpp
cache: apt
matrix:
   # =======================================================
   # DEBUG Build
   # =======================================================
   # D1. clang-mp-4.8     | DEBUG    
   #- CMAKE_CXX_COMPILER=clang-mp-3.4
   # CMAKE_BUILD_TYPE=DEBUG
   # D2. g++-mp-4.8     | DEBUG    
   - CMAKE_CXX_COMPILER=g++-4.8
     CMAKE_BUILD_TYPE=DEBUG
   # =======================================================
   # RELEASE Build
   # =======================================================
   # D1. clang-mp-4.8     | RELEASE   
   #- CMAKE_CXX_COMPILER=clang-mp-3.4
   #  CMAKE_BUILD_TYPE=RELEASE
   # D2. g++-mp-4.8     | RELEASE    
   #- CMAKE_CXX_COMPILER=g++-mp-4.8
   #  CMAKE_BUILD_TYPE=RELEASE

compiler:
  - g++-4.8

env:
 - CXX=g++-4.8
 - CC=gcc-4.8

before_install:
   - until sudo add-apt-repository -y ppa:saiarcot895/chromium-beta; do echo retyr; done
   - until sudo add-apt-repository --yes ppa:kalakris/cmake; do echo retry; done
   - until sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test; do echo retry; done
   - until sudo apt-get -qq update; do echo retry; done             

install:
  - until sudo apt-get install cmake; do echo retry; done
  - until sudo apt-get install ninja-build; do echo retry; done
  - until sudo apt-get -qq install libboost-all-dev libboost-test-dev libboost-program-options-dev; do echo retry; done
 
  
script:
  - mkdir -p build
  - cd build
  - GENERATOR=-GNinja;
  - /usr/bin/cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}  -DCMAKE_PROGRAM_PATH=/usr/bin  -DCMAKE_INSTALL_PREFIX=run ../;

after_failure: "cat /home/travis/build/seahorn/seahorn/build/llvm-prefix/src/llvm-stamp/llvm-configure-*.log"

after_script:
  - echo $CXX
  - echo $CC
  - CXX=g++-4.8 /usr/bin/cmake --build .
  - make
  - cd ..



notifications:
  email:
    recipients:
     - seahorn-build@googlegroups.com
    on_success: always
    on_failure: always